### ISSUE TITLE
Idea: Track Xcode version in archive digest identifier

### ISSUE THREAD

**Issue by mokagio** [guidomb/carthage_cache#25] opened 2016-11-11 20:12 UTC
One of my apps failed submission because the frameworks specified iOS 10.2 rather than 10.1.

<img width="1332" alt="screen shot 2016-11-12 at 7 06 16 am" src="https://cloud.githubusercontent.com/assets/1218433/20228849/651944d2-a8a7-11e6-8356-14b48201ff85.png">

Looking online it seems that the error I got from iTunesConnect matches the ones of people that have been trying to submit apps using Xcode Beta versions.

I am not 100% sure but I think this might be due to the framework being build on a Mac with Xcode 8.2 and uploaded, but the CI box that submitted the build to the app store is running Xcode 8.1.

If the version of Xcode had been used as part of the identifier of the archive this might not have happened.

Would it make sense though to do this? Or would it get in the way?

I can see this creating friction when Xcode updates but with no changes to the min sdk version of iOS.

Anyway... Just wanted to put this here to start the discussion 👍

**Comment by guidomb** [comment] 2016-11-11 21:02
I am sorry to hear that. Carthage cache currently uses a digest of the `Cartfile.resolved` plus the version of Swift. I think I assumed that if Xcode version changed the Swift version would change but that does not seem to be the case.

This is really annoying (thanks Apple for that).

Can you corroborate that the problem is the different version of XCode? If this is the case I think we could add the xcode version as part of the archive digest identifier. 

This is quite weird because if this compiles is actually an iTunes issue because if the swift compiler did not change everything should work.

Making the change is really simple is basically adding 

```ruby
`xcodebuild -version`.match(/Xcode ((\d+\.)?\d+\.\d+)/)[1]
```

to this function https://github.com/guidomb/carthage_cache/blob/master/lib/carthage_cache/carthage_resolved_file.rb#L35

But I don't want to add this unless is really necessary.

**Comment by mokagio** [comment] 2016-11-29 02:51
Hi, sorry for the intermittent feedback.

I'm still not 100% sure where the issue is, sorry 😞 . I'll keep you posted on this.

**Comment by guidomb** [comment] 2016-12-27 18:25
I've been using carhage_cache we both Xcode 7.2.1 and Xcode 8.2.1 and did not find any issues. I am closing this for now because it seems there is nothing to be done. Feel free to re-open it if you have any news. Thanks!

**Closed by guidomb** 2016-12-27 18:25 UTC
Labels: waiting-for-response
